### ISSUE TITLE
Using folder name of folder on project 

### ISSUE THREAD

**Issue by mauroreisvieira** [deathaxe/SwitchWindow#2]
First of all, very cool plugin.

It's possible when the Project is not defined show the name of the folder instead of `none`?

<img width="598" alt="Screenshot 2023-01-05 at 11 39 03 AM" src="https://user-images.githubusercontent.com/3084774/210772257-102f60f4-722c-473a-b59f-87886fb6f507.png">

**Comment by deathaxe** [comment]
You want the folder which is added to sidebar?

We could display the first one being added or maybe try to find the one belonging to the active view.

Should be possible.
