### ISSUE TITLE
Please make classic option "select" when release key like all Switch windows do

### ISSUE THREAD

**Issue by 9840380** [deathaxe/SwitchWindow#3]
Hi thanks for such nice program!!!
Can you please make classic option to switch windows when releasing keys

For example when i add hotkey to alt+tab, i want to automatically select selected window when release key alt, but when i hold alt and pressing tab it move next window.

Now i must additionally pressing enter every time i Switching Window with alt+tab.

**Comment by deathaxe** [comment]
I am not aware of a method to bind commands to "release key" events.
